dotnet test --filter CancellAllTasksAcceptedExceptedTasktaskManagementCancelAllTasks_AllTasksCancelPetitionAcceptedStatus
dotnet test --no-build --filter  CancellAllTasksAcceptedtaskManagementCancelAllTasks_AllTasksCancelPetitionAcceptedStatus
dotnet test --no-build --filter  TaskNotAcceptedCancellationTokenSourceNotFoundExceptedTasktaskManagementCancelAllTasks_OneOrMoreTasksPetitionNotAcceptedStatus
dotnet test --no-build --filter  TaskNotAcceptedCancellationTokenSourceNotFoundtaskManagementCancelAllTasks_OneOrMoreTasksPetitionNotAcceptedStatus

dotnet test --no-build --filter  CancellationTokenSourceNullCancelTask_TaskManagementRegister_CancellationTokenSourceNotFoundTaskStatus
dotnet test --no-build --filter  InputTaskNameEmptyCancelTask_TaskManagementRegister_NameInputNotFoundTaskStatus
dotnet test --no-build --filter  InputTaskNameNullCancelTask_TaskManagementRegister_NameInputNotFoundTaskStatus
dotnet test --no-build --filter  TaskNullNameNullCancelTask_TaskManagementRegister_TaskNotFoundTaskStatus
dotnet test --no-build --filter  TaskRegisteredCompletedCancelTask_TaskManagementRegister_CancellationTokenSourceNotFoundTaskStatus
dotnet test --no-build --filter  TaskRegisteredDoubleCancelTask_TaskManagementRegister_CancellationTokenSourceNotFoundTaskStatus
dotnet test --no-build --filter  TaskRegisteredFaultedCancelTask_TaskManagementRegister_CancellationTokenSourceNotFoundTaskStatus
dotnet test --no-build --filter  TaskRegisteredNotStartedCancelTask_TaskManagementRegister_CancellationTokenSourceNotFoundTaskStatus
dotnet test --no-build --filter  TaskRegisteredRunningCancelTask_TaskManagementRegister_CancellationTokenSourceNotFoundTaskStatus

dotnet test --no-build --filter  CheckAllTaskStatusCompletedTasksCompleted_TaskManagementCheckAllTaskStatusCompleted_AllTasksCompletedStatus
dotnet test --no-build --filter  CheckAllTaskStatusCompletedTasksCompletedExcepted_TaskManagementCheckAllTaskStatusCompleted_AllTasksCompletedStatus

dotnet test --no-build --filter  CompletedWithoutCancelsCheckTaskStatusCompleted_TaskManagementRegister_StartedTaskStatus
dotnet test --no-build --filter  InnerCancellationTokenCheckExceptionCheckTaskStatusCompleted_TaskManagementRegister_NotCompletedTaskStatus
dotnet test --no-build --filter  InputTaskNameEmptyCheckTaskStatusCompleted_TaskManagementRegister_NameInputNotFoundTaskStatus
dotnet test --no-build --filter  InputTaskNameNullCheckTaskStatusCompleted_TaskManagementRegister_NameInputNotFoundTaskStatus

dotnet test --no-build --filter  NotRegisteredDeleteTask_TaskManagementRegister_TaskNotFoundTaskStatus
dotnet test --no-build --filter  OnlyRegisteredDeleteTask_TaskManagementRegister_InvalidOperationException
dotnet test --no-build --filter  StartedDeleteTask_TaskManagementRegister_InvalidOperationException
dotnet test --no-build --filter  StartedWaitedCancellationTokenSourceNullCompletionDeleteTask_TaskManagementRegister_StartedTaskStatus
dotnet test --no-build --filter  StartedWaitedCompletionDeleteTask_TaskManagementRegister_StartedTaskStatus
dotnet test --no-build --filter  StartedWaitedCompletionDeleteTaskQueueActivated_TaskManagementRegister_StartedTaskStatus
dotnet test --no-build --filter  StartedWaitedCompletionDeleteTaskQueueDeactivated_TaskManagementRegister_StartedTaskStatus

dotnet test --no-build --filter  InputNameEmptyGetCancellationTokenSource_TaskManagementRegister_NameInputNotFoundTaskStatus
dotnet test --no-build --filter  InputNameNullGetCancellationTokenSource_TaskManagementRegister_NameInputNotFoundTaskStatus
dotnet test --no-build --filter  NoTaskRegisteredGetCancellationTokenSource_TaskManagementRegister_TaskNotFoundTaskStatus
dotnet test --no-build --filter  TaskRegisteredCancellationTokenSourceGetCancellationTokenSource_TaskManagementRegister_TaskNotFoundTaskStatus
dotnet test --no-build --filter  TaskRegisteredNullCancellationTokenSourceGetCancellationTokenSource_TaskManagementRegister_TaskNotFoundTaskStatus

dotnet test --no-build --filter  OneTaskNullCancellationTokenRegister_TaskManagementRegister_AddedTaskStatus
dotnet test --no-build --filter  OneTaskRegister_TaskManagementRegister_AddedTaskStatus
dotnet test --no-build --filter  OneTaskRegisterActionNull_TaskManagementRegister_NameInputNotFoundTaskStatus
dotnet test --no-build --filter  OneTaskRegisterNameEmpty_TaskManagementRegister_NameInputNotFoundTaskStatus
dotnet test --no-build --filter  OneTaskRegisterNameNull_TaskManagementRegister_NameInputNotFoundTaskStatus
dotnet test --no-build --filter  SameTaskRegister_TaskManagementRegister_AlreadyRegisteredTaskStatus

dotnet test --no-build --filter  StartOneTask_TaskManagementRegister_StartedTaskStatus
dotnet test --no-build --filter  StartSameTask_TaskManagementRegister_InvalidOperationForCurrentStateExceptionTaskStatus
dotnet test --no-build --filter  StartTaskNameEmpty_TaskManagementRegister_NameInputNotFoundTaskStatus
dotnet test --no-build --filter  StartTaskNameNull_TaskManagementRegister_NameInputNotFoundTaskStatus
