name: nuget packages release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
env:
  DOTNET_VERSION: '2.2.110'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: |
        cd src
        dotnet restore NetFramework.Task.Management
    - name: Build
      run: |
        cd src
        cd NetFramework.Task.Management
        dotnet build NetFramework.Tasks.Management.csproj --configuration Release /p:Version=${VERSION}
    - name: Pack
      run: | 
        cd src
        cd NetFramework.Task.Management
        dotnet pack NetFramework.Tasks.Management.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push NetFramework.Tasks.Management.${VERSION}.nupkg --source https://nuget.pkg.github.com/ryujose/index.json --api-key ${NUGET_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_TOKEN }}
